### ISSUE TITLE
field_at should ignore EcsIterCppEach

### ISSUE THREAD

**Issue by farnoy** [Indra-db/Flecs-Rust#155]
In Flex-Rust, `field_at()` is implemented in terms of `field()`, which does the check for EcsIterCppEach. This is [not done upstream](https://github.com/SanderMertens/flecs/blob/b0a4fe620c2896fc2a314761c7e8bff7d5490871/flecs.h#L22602-L22611). The only thing that seems to work without setting the flag at the moment is `field_at_untyped()`

**Comment by Indra-db** [comment]
fixed, thanks! I will introduce this in the next minor version later today
