### ISSUE TITLE
`#[derive(Component)]` doesn't verify that the component is `Send + Sync`

### ISSUE THREAD

**Issue by AlfredAn** [Indra-db/Flecs-Rust#161]
```rust
use flecs_ecs::prelude::*;
use std::rc::Rc;

#[derive(Component)]
struct Foo(Rc<u8>);

fn main() {
    let world = World::new();
    world.set(Foo(Rc::new(0)));
}
```

This creates the following impls, even though `Foo` shouldn't implement `Sync`.
```rust
unsafe impl Send for Foo {}
unsafe impl Sync for Foo {}
```

I feel like this example should probably be a compile error instead, and have the user manually add the impls if they know what they are doing.

**Comment by Indra-db** [comment]
Thanks! Solved, didn't implement that one correctly.
