### ISSUE TITLE
Send + Sync Commit Question

### ISSUE THREAD

**Issue by JtotheThree** [Indra-db/Flecs-Rust#166]
I've been playing with this crate for a gdext rust Godot project.

Before the Send + Sync commit for Component requirement, I was able to store Gd<> objects into a component struct like

#[derive(Component)]
struct Node2DComponent(Gd<Node2D>);

After the Send + Sync commit this is no longer possible because Gd<> doesn't implement Send + Sync. 

Is Flecs running pipelines multi-threaded? I.e. even if the the system itself is set to single-threaded there's still possible multi-threaded access to a component from another system? If that is the case I can see where this would cause unexpected behavior.  I haven't toyed with this enough to add enough systems for it to be an issue yet. 

Obviously if you're forced into single threaded because you're storing position data in a Gd<Node> that's forced single-threaded you're losing out on a lot of performance potential of ECS, but for systems where you're not trying to squeeze every last bit of performance you can it's quite convenient. 

I've tested the performance on doing sync query loops to say, update Node2D.SetPosition from a Position component every frame, but even optimized that still consumes about 0.5-1ms of a frame for 2k entities. I guess the other alternative is doing a MultiMesh rendering system?

**Comment by Indra-db** [comment]
That was a bad implementation on my part, beforehand, it was being implemented on all component types unsafely within flecs_rust, which was a mistake. Now it requires the User to do so correctly themself, if needed. 

You can still implement Send and Sync on the types by doing so unsafely when you're sure it's not a problem. 

```
unsafe impl Send for ...
unsafe impl Sync for ...
```

> Is Flecs running pipelines multi-threaded? I.e. even if the the system itself is set to single-threaded there's still possible multi-threaded access to a component from another system? If that is the case I can see where this would cause unexpected behavior. I haven't toyed with this enough to add enough systems for it to be an issue yet.

Flecs is not running multiple pipelines multi-threaded. Technically speaking it is possible, but you have to be very careful. It's not something that is done generally speaking. 

Yes a component can be accessed in multi-threaded context from another system. 

> I've tested the performance on doing sync query loops to say, update Node2D.SetPosition from a Position component every frame, but even optimized that still consumes about 0.5-1ms of a frame for 2k entities. I guess the other alternative is doing a MultiMesh rendering system?

1ms for 2000 entities? That seems horrendous. I'm not sure what's going wrong there? If you have a test case for me to test out, I can take a look. 

For reference, this is the performance I get on an M3 max macbook: 
```
1024 tables 1M entities query over 2 components Position and Velocity doing pos.x += vel.x, same with y

time:   [331.51 µs 335.22 µs 339.37 µs]
```

**Comment by Indra-db** [comment]
Previously you were putting a non send type in a component, now that is correctly disallowed since you could access it from other threads. As I mentioned before, you could mark it unsafely if they are sure they won't access it incorrectly, otherwise you can store the data outside the ECS and sync it manually which I think is what you were saying in the last bit, not sure
